import { createSchema, defaultModel } from '..';

export default createSchema({
  id: defaultModel.stringUnique,
  interval: defaultModel.string,
  startAt: defaultModel.date,
  endAt: defaultModel.date,
  addressNew: defaultModel.number,
  addressSummary: defaultModel.object,
  addressTotal: defaultModel.number,
  pointNew: defaultModel.number,
  pointTotal: defaultModel.number,
  swapCount: defaultModel.number,
  swapCountSummary: defaultModel.object,
  swapCountTotal: defaultModel.number,
  swapVolume: defaultModel.number,
  swapVolumeSummary: defaultModel.object,
  swapVolumeTotal: defaultModel.number,
  transactionCount: defaultModel.number,
  transactionCountSummary: defaultModel.object,
  transactionCountTotal: defaultModel.number,
  transactionVolume: defaultModel.number,
  transactionVolumeSummary: defaultModel.object,
  transactionVolumeTotal: defaultModel.number,
  userActive: defaultModel.number,
  userAccountActive: defaultModel.number,
  userNew: defaultModel.number,
  userTotal: defaultModel.number,
  userTempActive: defaultModel.number,
  userTempNew: defaultModel.number,
  userTempTotal: defaultModel.number,
  swapUser: defaultModel.number,
  swapAddress: defaultModel.number,
  swapUserSummary: defaultModel.array,
  swapAddressSummary: defaultModel.array,

}, 'DashboardData', null, null);

export interface DashboardInterface {
  id?: string,
  interval?: string,
  startAt?: Date,
  endAt?: Date,
  addressNew?: number,
  addressSummary?: object,
  addressTotal?: number,
  pointNew?: number,
  pointTotal?: number,
  swapCount?: number,
  swapCountSummary?: object,
  swapCountTotal?: number,
  swapVolume?: number,
  swapVolumeSummary?: object,
  swapVolumeTotal?: number,
  transactionCount?: number,
  transactionCountSummary?: object,
  transactionCountTotal?: number,
  transactionVolume?: number,
  transactionVolumeSummary?: object,
  transactionVolumeTotal?: number,
  userActive?: number,
  userAccountActive?: number,
  userNew?: number,
  userTotal?: number,
  userTempActive?: number,
  userTempNew?: number,
  userTempTotal?: number,
  swapUser?: number,
  swapAddress?: number,
  swapUserSummary?: [],
  swapAddressSummary?: [],
}

export interface DashboardFiledResponse {
  _id?: 0 | 1,
  id?: 0 | 1,
  interval?: 0 | 1,
  startAt?: 0 | 1,
  endAt?: 0 | 1,
  addressNew?: 0 | 1,
  addressSummary?: 0 | 1,
  addressTotal?: 0 | 1,
  pointNew?: 0 | 1,
  pointTotal?: 0 | 1,
  swapCount?: 0 | 1,
  swapCountSummary?: 0 | 1,
  swapCountTotal?: 0 | 1,
  swapVolume?: 0 | 1,
  swapVolumeSummary?: 0 | 1,
  swapVolumeTotal?: 0 | 1,
  transactionCount?: 0 | 1,
  transactionCountSummary?: 0 | 1,
  transactionCountTotal?: 0 | 1,
  transactionVolume?: 0 | 1,
  transactionVolumeSummary?: 0 | 1,
  transactionVolumeTotal?: 0 | 1,
  userActive?: 0 | 1,
  userAccountActive?: 0 | 1,
  userNew?: 0 | 1,
  userTotal?: 0 | 1,
  userTempActive?: 0 | 1,
  userTempNew?: 0 | 1,
  userTempTotal?: 0 | 1,
  swapUser?: 0 | 1,
  swapAddress?: 0 | 1,
  swapUserSummary?: 0 | 1,
  swapAddressSummary?: 0 | 1,
}
