import { createSchema, defaultModel } from '..';

export default createSchema({
  id: defaultModel.stringUnique,
  interval: defaultModel.string,
  startAt: defaultModel.date,
  endAt: defaultModel.date,
  addressNew: defaultModel.number,
  addressSummary: defaultModel.object,
  addressTotal: defaultModel.number,
  pointNew: defaultModel.number,
  pointTotal: defaultModel.number,
  swapCount: defaultModel.number,
  swapCountSummary: defaultModel.object,
  swapCountTotal: defaultModel.number,
  swapVolume: defaultModel.number,
  swapVolumeSummary: defaultModel.object,
  swapVolumeTotal: defaultModel.number,
  transactionCount: defaultModel.number,
  transactionCountSummary: defaultModel.object,
  transactionCountTotal: defaultModel.number,
  transactionVolume: defaultModel.number,
  transactionVolumeSummary: defaultModel.object,
  transactionVolumeTotal: defaultModel.number,
  userActive: defaultModel.number,
  userAccountActive: defaultModel.number,
  userNew: defaultModel.number,
  userTotal: defaultModel.number,
  userTempActive: defaultModel.number,
  userTempNew: defaultModel.number,
  userTempTotal: defaultModel.number,
}, 'DashboardData', null, null);
