export const data = '';

export default data;

export const CHAIN_TYPE = {
  // System
  customCreate: 'customCreate',
  custom: 'custom',
  multiChain: 'multiChain',
  evm: 'evm',
  hardwareWallet: 'hardwareWallet',
  trezor: 'trezor',
  // EVM
  ETH: 'ether',
  BSC: 'binanceSmart',
  kucoin: 'kucoin',
  boba: 'boba',
  arbitrum: 'arbitrum',
  arbitrumXdai: 'arbitrumXdai',
  optimism: 'optimism',
  binanceSmart: 'binanceSmart',
  fantom: 'fantom',
  matic: 'matic',
  tomo: 'tomo',
  binance: 'binance',
  ether: 'ether',
  etherPoW: 'etherPoW',
  celo: 'celo',
  heco: 'heco',
  doge: 'doge',
  xDai: 'xDai',
  xdai: 'xdai',
  kardia: 'kardia',
  ronin: 'ronin',
  okex: 'okex',
  klaytn: 'klaytn',
  gate: 'gate',
  harmony: 'harmony', // Bech32 Address Chain
  aurora: 'aurora',
  zksync: 'zksync',
  starknet: 'starknet',
  bittorrent: 'bittorrent',
  thetaFuel: 'thetaFuel',
  platon: 'platon',
  moonbeam: 'moonbeam',
  // Cosmos
  terra2: 'terra2',
  secretNetwork: 'secretNetwork',
  kava: 'kava',
  band: 'band',
  cosmos: 'cosmos',
  thor: 'thor',
  terra: 'terra',
  persistence: 'persistence',
  functionX: 'functionX',
  sei: 'sei',
  injective: 'injective',
  osmosis: 'osmosis',
  evmos: 'evmos',
  juno: 'juno',
  agoric: 'agoric',
  archway: 'archway',
  kaneda: 'kaneda',
  oasis: 'oasis',
  kujira: 'kujira',
  stargaze: 'stargaze',
  umee: 'umee',
  stride: 'stride',
  cronos: 'cronos',
  // Tron
  TRX: 'tron',
  tron: 'tron',
  // Avax X | P | C
  avax: 'avax',
  avaxX: 'avaxX',
  // DOT
  polkadot: 'polkadot',
  kusama: 'kusama',
  // Move Base
  aptos: 'aptos',
  aptosDev: 'aptosDev',
  aptosLabs: 'aptosLabs',
  sui: 'sui',

  // Others
  bitcoin: 'bitcoin',
  solana: 'solana',
  link: 'link',
  near: 'near',
  eos: 'eos',
  elrond: 'elrond',
  conflux: 'conflux',
  tezos: 'tezos',
  algorand: 'algorand',
  theta: 'theta',
  ton: 'ton',
  casper: 'casper',
} as const;
export const COIN_IMAGE = {
  BTC: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BTC.png',
  ETH: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ETH.png',
  ETHARB:
        'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/arbitrum_eth.png',
  ETHA0X:
        'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/arbitrum_xdai.png',
  OP: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/op.png',
  BOBA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/boba_eth.png',
  KCS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kucoin.png',
  BNB: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BNBVer2.png',
  HT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/heco.png',
  TOMO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/Tomo.png',
  USDT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/USDT.jpg',
  AVAX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/avax.png',
  KSM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kusama.png',
  NEAR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/near.png',
  DOT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/dot.png',
  C98: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/coin98.png',
  TRX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/tron.png',
  CELO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/celo.png',
  SOL: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/solana.jpg',
  SRM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/serum.jpg',
  ATOM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/cosmos.png',
  RUNE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/thor.png',
  LUNA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/terra.png',
  LUNA2: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/terra2.png',
  KAVA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/kava.png',
  SCRT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/secretNetwork.png',
  EGLD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/elrond.png',
  XTZ: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/tezos.png',
  ONE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/harmony.png',
  CFX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/conflux.png',
  AURORA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/aurora.png',

  BAND: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/band.png',
  FTM: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/fantom.png',
  MATIC: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/polygon.png',
  XPRT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/persistance.png',
  XDAI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_xdai.png',
  KAI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_kardia.png',
  RON: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_ronin.png',
  OKT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_okex.png',
  GT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_gate.png',
  KLAY: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_klaytn.png',
  CRO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/CRO.png',
  BTT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/BTT.png',
  HNT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_hnt.png',
  FLOW: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/ic_flow.png',
  THETA: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/THETA.png',
  GLMR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/GMLR.png',
  LAT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/LAT.png',
  TON: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/TON.png',
  TFUEL: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/TFUEL.png',
  ALGO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/algorand.png',
  CSPR: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Coin/casper.png',
  FX: 'https://coin98.s3.ap-southeast-1.amazonaws.com/fx.png',

  APT: 'https://coin98.s3.ap-southeast-1.amazonaws.com/aptos.jpg',
  SUI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/sui.jpg',
  SEI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/sei.png',
  INJ: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/injective.png',
  EVMOS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/evmos.png',
  JUNO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/juno.png',
  KUJI: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/kuji.png',
  OSMO: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/osmo.png',
  ROSE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/oasis.png',
  STARS: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/stars.png',
  STRD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/stride.png',
  UMEE: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/umee.png',
  BLD: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/agoric.png',
  CONST: 'https://coin98.s3.ap-southeast-1.amazonaws.com/Currency/archway.png',
};
export const CHAIN_DATA = {
  multiChain: {
    isSystem: true,
    isMnemonicOnly: true,
    name: 'Multi-Chain',
    icon: 'app_multi_chain',
    chain: CHAIN_TYPE.multiChain,
    tokenStandard: 'All Blockchains',
  },

  evm: {
    isSystem: true,
    name: 'EVM Wallet',
    icon: 'app_evm',
    chain: CHAIN_TYPE.evm,
    tokenStandard: 'EVM Wallet',
    isExcluded: true,
  },

  hardwareWallet: {
    isSystem: true,
    isHardware: true,
    name: 'Hardware Wallet',
    icon: 'app_ledger',
    chain: CHAIN_TYPE.hardwareWallet,
    tokenStandard: 'Ledger, Trezor',
  },

  customCreate: {
    isSystem: true,
    name: 'Custom Network',
    icon: 'app_custom_network',
    chain: CHAIN_TYPE.customCreate,
    tokenStandard: 'Create Custom Network',
    isExcluded: true,
  },
  custom: {
    isSystem: true,
    name: 'Custom Network',
    icon: 'app_box',
    chain: CHAIN_TYPE.custom,
    tokenStandard: 'Custom Network',
    isExcluded: true,
  },
  // bitcoin: {
  //   order: 5,
  //   isFee: true,
  //   isMnemonicOnly: true,
  //   icon: 'app_bitcoin',
  //   id: 'bitcoin',
  //   name: 'Bitcoin',
  //   shortName: 'Bitcoin',
  //   logo: COIN_IMAGE.BTC,
  //   symbol: 'BTC',
  //   chain: CHAIN_TYPE.bitcoin,
  //   tokenStandard: 'BTC',
  //   scan: 'https://www.blockchain.com/btc'
  // },
  ether: {
    numChainId: 1,
    chainId: '0x1',
    order: 1,
    isToken: true,
    standard: 'ERC20',
    nftStandard: 'ERC721',
    balanceContract: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    icon: 'app_ethereum',
    id: 'ethereum',
    name: 'Ethereum',
    shortName: 'Ethereum',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.ether,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.infura.io/v3/92d53cee52834368b0fabb42fa1b5570',
    scan: 'https://etherscan.io',
  },
  binanceSmart: {
    numChainId: 56,
    chainId: '0x38',
    order: 1,
    isToken: true,
    isSupportedNFT: true,
    nftStandard: 'BEP721',
    standard: 'BEP20',
    replacementSymbol: 'BSC',
    balanceContract: '0xA6762c710852681c4593C10c4304C5211FB2122c',
    multiTransferContract: '0x2E1D30460265bFEBedacf5bb6f9A80F0E74B7498',

    subName: 'BSC',

    isWeb3: true,
    isFee: true,
    icon: 'app_binance',

    id: 'binancecoin',
    name: 'BNB Smart Chain',
    shortName: 'BSC',
    logo: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: CHAIN_TYPE.binanceSmart,
    tokenStandard: 'BNB BEP20',
    rpcURL: 'https://binance.nodereal.io',
    // rpcURL: 'https://bsc-mainnet.nodereal.io/v1/68ac333c4bc646df8ef23fe996dd6d83',
    // scan: 'https://bscscan.com',
  },
  heco: {
    numChainId: 128,
    chainId: '0x80',
    order: 1,
    isToken: true,
    isSupportedNFT: true,
    standard: 'HRC20',
    nftStandard: 'HRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_heco',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    isSupportedEIP1559: true,

    id: 'huobi-token',
    name: 'HECO Chain',
    shortName: 'Huobi',
    logo: COIN_IMAGE.HT,
    symbol: 'HT',
    chain: CHAIN_TYPE.heco,
    tokenStandard: 'HT HRC20',
    rpcURL: 'https://http-mainnet.hecochain.com',
    scan: 'https://hecoinfo.com',
  },
  okex: {
    numChainId: 66,
    chainId: '0x42',
    order: 2,
    balanceContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isToken: true,
    isSupportedNFT: true,
    id: 'oec-token',
    name: 'OKX Chain',
    icon: 'app_okex',
    symbol: 'OKT',
    chain: CHAIN_TYPE.okex,
    logo: COIN_IMAGE.OKT,
    standard: 'KIP20',
    nftStandard: 'NFT',
    tokenStandard: 'OKT KIP10 KIP20 NFT',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://exchainrpc.okex.org',
    scan: 'https://www.oklink.com/okexchain',
  },
  gate: {
    numChainId: 86,
    chainId: '0x56',
    order: 2,
    balanceContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multiTransferContract: '0x963e1bcd1f82724bd8fa16a3b6962d100fb287fc',
    isSupportedNFT: true,
    isToken: true,
    id: 'gatechain-token',
    name: 'GateChain',
    icon: 'app_gate',
    symbol: 'GT',
    chain: CHAIN_TYPE.gate,
    logo: COIN_IMAGE.GT,
    standard: 'GRC20',
    nftStandard: 'GRC721',
    tokenStandard: 'GT GRC20 GRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://evm.gatenode.cc',
    scan: 'https://gatescan.org',
  },

  kucoin: {
    numChainId: 321,
    chainId: '0x141',

    order: 2,
    isSupportedNFT: true,
    isToken: true,
    subName: 'KCS',
    standard: 'KRC20',
    nftStandard: 'KRC721',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    isWeb3: true,
    isFee: true,
    icon: 'kucoin',
    id: 'kucoin-shares',
    name: 'Kucoin Chain',
    shortName: 'KCC',
    logo: COIN_IMAGE.KCS,
    symbol: 'KCS',
    chain: CHAIN_TYPE.kucoin,
    tokenStandard: 'KCS KRC20 KRC721',
    rpcURL: 'https://rpc-mainnet.kcc.network',
    scan: 'https://explorer.kcc.io/en',
  },
  solana: {
    order: 1,
    isToken: true,
    standard: 'SPL',
    nftStandard: 'SPL NFT',
    isSupportedNFT: true,
    multiTransferContract: true,
    icon: 'app_solana',
    id: 'solana',
    name: 'Solana',
    shortName: 'Solana',
    logo: COIN_IMAGE.SOL,
    symbol: 'SOL',
    chain: CHAIN_TYPE.solana,
    tokenStandard: 'SOL SPL',
    rpcURL: 'https://information.coin98.com/api/solanaV4',
    scan: 'https://solscan.io',
  },
  near: {
    order: 2,
    icon: 'app_near',
    id: 'near',
    name: 'Near',
    logo: COIN_IMAGE.NEAR,
    symbol: 'NEAR',
    tokenStandard: 'NEAR NEP141',
    standard: 'NEP141',
    chain: CHAIN_TYPE.near,

    isToken: true,
    scan: 'https://explorer.near.org',
    rpcURL: 'https://rpc.mainnet.near.org',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'accounts',
    // isToken: true
  },
  avax: {
    path: 9000,

    numChainId: 43114,
    chainId: '0xa86a',

    order: 1,
    isToken: true,
    nftStandard: 'ARC721',
    standard: 'ARC20',
    replacementSymbol: 'CCHAIN',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',

    subName: 'C',
    isSupportedNFT: true,

    isWeb3: true,
    isFee: true,
    icon: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche C-Chain',
    shortName: 'Avalanche',
    logo: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: CHAIN_TYPE.avax,
    tokenStandard: 'AVAX-C ARC20',
    rpcURL: 'https://api.avax.network/ext/bc/C/rpc',
    scan: 'https://snowtrace.io',
  },
  avaxX: {
    order: 5,
    replacementSymbol: 'XCHAIN',
    subName: 'X',
    icon: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche X-Chain',
    shortName: 'Avalanche',
    logo: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: CHAIN_TYPE.avaxX,
    tokenStandard: 'AVAX-X',
    scan: 'https://avascan.info/blockchain/x',
  },
  tron: {
    order: 1,
    isToken: true,
    standard: 'TRC20',
    // trcSubName: 'TRC10',
    icon: 'app_tron',
    id: 'tron',
    name: 'Tron',
    shortName: 'Tron',
    logo: COIN_IMAGE.TRX,
    symbol: 'TRX',
    chain: CHAIN_TYPE.tron,
    tokenStandard: 'TRX TRC10 TRC20',
    scan: 'https://tronscan.org/#',
    scanTxPrefix: 'transaction',
  },
  matic: {
    numChainId: 137,
    chainId: '0x89',
    order: 2,
    isToken: true,
    standard: 'PRC20',
    nftStandard: 'PRC721',
    isFee: true,
    isWeb3: true,
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    // //nftMint: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',

    isSupportedNFT: true,
    id: 'matic-network',
    name: 'Polygon',
    icon: 'app_polygon',
    logo: COIN_IMAGE.MATIC,
    symbol: 'MATIC',
    chain: CHAIN_TYPE.matic,
    tokenStandard: 'MATIC PRC20',
    rpcURL: 'https://rpc-mainnet.maticvigil.com/',
    scan: 'https://polygonscan.com',
  },
  fantom: {
    numChainId: 250,
    chainId: '0xfa',
    order: 2,
    isToken: true,
    standard: 'FRC20',
    nftStandard: 'FRC721',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    // //nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    isFee: true,
    isWeb3: true,
    isSupportedNFT: true,
    isSupportedV2: true,
    id: 'fantom',
    name: 'Fantom',
    icon: 'app_fantom',
    logo: COIN_IMAGE.FTM,
    symbol: 'FTM',
    chain: CHAIN_TYPE.fantom,
    tokenStandard: 'FANTOM FRC20',
    rpcURL: 'https://rpcapi.fantom.network',
    scan: 'https://ftmscan.com',
  },
  xDai: {
    isSupportedEIP1559: true,
    numChainId: 100,
    chainId: '0x64',
    order: 2,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    // //nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isToken: true,
    id: 'xdai',
    isSupportedNFT: true,
    name: 'Gnosis Chain',
    icon: 'app_xDai',
    symbol: 'XDAI',
    chain: CHAIN_TYPE.xDai,
    logo: COIN_IMAGE.XDAI,
    standard: 'XRC20',
    nftStandard: 'XRC721',
    tokenStandard: 'XDAI XRC20',
    isFee: true,
    isWeb3: true,
    // rpcURL: 'https://rpc.xdaichain.com',
    rpcURL: 'https://xdai-rpc.gateway.pokt.network',
    scan: 'https://blockscout.com/xdai/mainnet',
  },
  polkadot: {
    order: 3,
    icon: 'app_polkadot',
    isMnemonicOnly: true,
    id: 'polkadot',
    name: 'Polkadot',
    shortName: 'Polkadot',
    logo: COIN_IMAGE.DOT,
    symbol: 'DOT',
    chain: CHAIN_TYPE.polkadot,
    tokenStandard: 'DOT',
    rpcURL: 'rpc.polkadot.io',
    scan: 'https://polkadot.subscan.io',
    scanTxPrefix: 'extrinsic',
    scanAddressPrefix: 'account',
  },
  kusama: {
    order: 3,
    icon: 'app_kusama',

    isMnemonicOnly: true,
    id: 'kusama',
    name: 'Kusama',
    shortName: 'Kusama',
    logo: COIN_IMAGE.KSM,
    symbol: 'KSM',
    chain: CHAIN_TYPE.kusama,
    tokenStandard: 'KSM',
    rpcURL: 'kusama-rpc.polkadot.io',
    scan: 'https://kusama.subscan.io',
    scanTxPrefix: 'extrinsic',
  },
  cosmos: {
    prefix: 'cosmos',
    path: 118,

    order: 3,
    isFactory: true,
    isCosmos: true,
    isMemo: true,
    id: 'cosmos',
    chainId: 'cosmoshub-4',
    name: 'Cosmos',
    icon: 'app_cosmos',
    symbol: 'ATOM',
    logo: COIN_IMAGE.ATOM,
    chain: CHAIN_TYPE.cosmos,
    tokenStandard: 'ATOM',
    scan: 'https://www.mintscan.io/cosmos',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'blocks/id',
  },
  thor: {
    prefix: 'thor',
    path: 931,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    id: 'thorchain',
    chainId: 'thorchain-mainnet-v1',
    name: 'THORChain',
    icon: 'app_thorchain',
    logo: COIN_IMAGE.RUNE,
    symbol: 'RUNE',
    chain: CHAIN_TYPE.thor,
    tokenStandard: 'RUNE',
    scan: 'https://viewblock.io/thorchain',
  },
  terra: {
    prefix: 'terra',
    path: 330,
    order: 3,
    isToken: true,
    standard: 'CW20',

    isCosmos: true,
    isMemo: true,

    id: 'terra-luna',
    name: 'Terra',
    icon: 'app_terra',
    symbol: 'LUNA',
    logo: COIN_IMAGE.LUNA,
    chain: CHAIN_TYPE.terra,
    tokenStandard: 'LUNA CW20',
    scan: 'https://finder.terra.money/columbus-5',
  },
  terra2: {
    prefix: 'terra',
    path: 330,

    order: 3,
    isToken: true,
    standard: 'CW20',

    isCosmos: true,
    isMemo: true,

    id: 'terra-luna-2',
    chainId: 'phoenix-1',

    name: 'Terra 2.0',
    icon: 'app_terra2',
    symbol: 'LUNA',
    logo: COIN_IMAGE.LUNA2,
    chain: CHAIN_TYPE.terra2,
    tokenStandard: 'LUNA CW20',
    scan: 'https://finder.terra.money/mainnet',
  },
  band: {
    prefix: 'band',
    path: 494,

    order: 3,
    isCosmos: true,
    isMemo: true,
    id: 'band-protocol',
    name: 'BandChain',
    icon: 'app_band',
    logo: COIN_IMAGE.BAND,
    symbol: 'BAND',
    tokenStandard: 'BAND',
    chain: CHAIN_TYPE.band,
    scan: 'https://cosmoscan.io',
    scanAddressPrefix: 'account',
  },
  kava: {
    prefix: 'kava',
    path: 459,
    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    id: 'kava',
    name: 'Kava',
    chainId: 'kava_2222-10',
    icon: 'app_kava',
    logo: COIN_IMAGE.KAVA,
    symbol: 'KAVA',
    chain: CHAIN_TYPE.kava,
    tokenStandard: 'KAVA',
    scan: 'https://www.mintscan.io/kava',
    rpcURL: 'https://kava4.data.kava.io',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'blocks/id',
  },

  secretNetwork: {
    prefix: 'secret',
    path: 529,

    order: 3,
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'secret',
    chainId: 'secret-4',
    name: 'Secret Network',
    icon: 'app_secret_network',
    logo: COIN_IMAGE.SCRT,
    symbol: 'SCRT',
    chain: CHAIN_TYPE.secretNetwork,
    tokenStandard: 'SCRT',
    rpcURL: 'https://lcd-secret.keplr.app',
    scan: 'https://secretnodes.com/secret/chains/secret-4',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'blocks/id',
  },

  persistence: {
    prefix: 'persistence',
    path: 750,

    order: 3,
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'persistence',
    chainId: 'core-1',
    name: 'Persistence',
    icon: 'app_persistence',
    logo: COIN_IMAGE.XPRT,
    symbol: 'XPRT',
    chain: CHAIN_TYPE.persistence,
    tokenStandard: 'XPRT',
    scan: 'https://explorer.persistence.one',
    scanBlockPrefix: 'blocks',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'wallet',
  },

  binance: {
    prefix: 'bnb',
    path: 714,

    order: 2,
    isToken: true,
    standard: 'BEP2',
    replacementSymbol: 'BC',

    isCosmos: true,
    isMemo: true,
    subName: 'BC',

    icon: 'app_binance',

    id: 'binancecoin',
    name: 'BNB Beacon Chain',
    shortName: 'Binance',
    logo: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: CHAIN_TYPE.binance,
    tokenStandard: 'BNB BEP2 BEP8',
    scan: 'https://explorer.binance.org',
  },

  functionX: {
    prefix: 'fx',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,

    chainId: 'fxcore',
    id: 'fx-coin',
    name: 'Function X',
    icon: 'app_functionX',
    symbol: 'FX',
    logo: COIN_IMAGE.FX,
    chain: CHAIN_TYPE.functionX,
    tokenStandard: 'FX FXRC20',
    scan: 'https://explorer.functionx.io/fxcore',
    rpcURL: 'https://fx-json.functionx.io:26657',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },

  elrond: {
    isLibrary: true,

    prefix: 'erd',
    path: 508,
    nftStandard: 'SFT',
    order: 3,
    defaultFee: 0.00005,
    isToken: true,
    standard: 'ESDT',

    id: 'elrond-erd-2',
    name: 'Elrond',
    icon: 'app_elrond',
    logo: COIN_IMAGE.EGLD,
    symbol: 'EGLD',
    chain: CHAIN_TYPE.elrond,
    tokenStandard: 'EGLD ESDT SFT',
    scan: 'https://explorer.elrond.com',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'accounts',
    scanBlockPrefix: 'blocks',
  },
  tezos: {
    isLibrary: true,
    defaultFee: 0.0015,

    prefix: 'tz1',
    path: 1729,
    nftStandard: 'FA2',
    isToken: true,
    standard: 'FA1.2',
    order: 2,

    id: 'tezos',
    name: 'Tezos',
    icon: 'app_tezos',
    logo: COIN_IMAGE.XTZ,
    symbol: 'XTZ',
    chain: CHAIN_TYPE.tezos,
    tokenStandard: 'XTZ FA1.2 FA2',
    scan: 'https://tezblock.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'block',
  },

  tomo: {
    path: 889,

    numChainId: 88,
    chainId: '0x58',

    order: 2,
    isToken: true,
    standard: 'TRC21',
    nftStandard: 'TRC721',
    isSupportedNFT: true,
    // nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',

    isWeb3: true,
    isFee: true,
    icon: 'app_tomochain',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',

    id: 'tomochain',
    name: 'TomoChain',
    shortName: 'Tomo',
    logo: COIN_IMAGE.TOMO,
    symbol: 'TOMO',
    chain: CHAIN_TYPE.tomo,
    tokenStandard: 'TOMO TRC21',
    rpcURL: 'https://rpc.tomochain.com',
    scan: 'https://scan.tomochain.com',
  },

  algorand: {
    defaultFee: 0.001,

    standard: 'ALGO',
    nftStandard: 'ALGO721',
    isToken: true,
    id: 'algorand',
    name: 'Algorand',
    icon: 'app_algorand',
    logo: COIN_IMAGE.ALGO,
    symbol: 'ALGO',
    chain: CHAIN_TYPE.algorand,
    tokenStandard: 'ALGO ALGO721',
    scan: 'https://algoexplorer.io',
  },
  casper: {
    standard: 'CSPR',
    nftStandard: 'CSPR-NFT',
    id: 'casper-network',
    name: 'Casper',
    icon: 'app_casper',
    logo: COIN_IMAGE.CSPR,
    symbol: 'CSPR',
    chain: CHAIN_TYPE.casper,
    tokenStandard: 'CSPR',
    scanTxPrefix: 'deploy',
    scanAddressPrefix: 'account',
    scan: 'https://cspr.live',
  },

  kardia: {
    numChainId: 24,
    chainId: '0x18',

    order: 2,
    isToken: true,
    id: 'kardiachain',
    name: 'KardiaChain',
    icon: 'app_kardia',
    symbol: 'KAI',
    chain: CHAIN_TYPE.kardia,
    logo: COIN_IMAGE.KAI,
    subName: 'KAI',
    standard: 'KRC20',
    nftStandard: 'KRC721',
    tokenStandard: 'KAI KRC20 KRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://rpc.kardiachain.io',
    scan: 'https://explorer.kardiachain.io',

    balanceContract: '0x8ef3C4Bf105Ec17cbeD7615C5711d2F4D44a4194',
    multiTransferContract: '0xf21201135568A81c9046d60a003eC2B883173F2f',
    // nftMint: '0x8347CD0aaF874259e9d577BeE08231F648C3fc29'
  },
  ronin: {
    prefix: 'ronin:',

    numChainId: 2020,
    chainId: '0x7e4',

    order: 2,
    isSupportedNFT: true,
    isToken: true,
    id: 'ronin',
    name: 'Ronin',
    icon: 'app_ronin',
    nftStandard: 'RRC721',
    symbol: 'RON',
    chain: CHAIN_TYPE.ronin,
    logo: COIN_IMAGE.RON,
    standard: 'RRC20',
    tokenStandard: 'RON RRC20 RRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://api.roninchain.com/rpc',
    scan: 'https://explorer.roninchain.com',
  },
  celo: {
    // mainAddress: '0x471ece3750da237f93b8e339c536989b8978a438',
    path: 52752,
    isFee: true,
    numChainId: 42220,
    chainId: '0xA4EC',
    order: 1,
    isSupportedNFT: true,
    isToken: true,
    balanceContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isWeb3: true,
    icon: 'app_celo',
    id: 'celo',
    name: 'Celo',
    shortName: 'Celo',
    logo: COIN_IMAGE.CELO,
    symbol: 'CELO',
    chain: CHAIN_TYPE.celo,
    tokenStandard: 'CELO CUSD',
    nftStandard: 'CELO721',
    rpcURL: 'https://forno.celo.org',
    scan: 'https://explorer.celo.org',
  },
  klaytn: {
    numChainId: 8217,
    chainId: '0x2019',

    order: 2,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',

    isSupportedNFT: true,
    isToken: true,
    id: 'klay-token',
    name: 'Klaytn',
    icon: 'app_klaytn',
    symbol: 'KLAY',
    standard: 'KIP7',
    nftStandard: 'KIP37',

    chain: CHAIN_TYPE.klaytn,
    logo: COIN_IMAGE.KLAY,
    tokenStandard: 'KLAY KIP7 KIP37',
    isFee: true,
    isWeb3: true,
    scan: 'https://scope.klaytn.com',
    // rpcURL: 'https://kaikas.cypress.klaytn.net:8651',
    rpcURL: 'https://public-node-api.klaytnapi.com/v1/cypress',
    scanAddressPrefix: 'account',
  },
  //
  harmony: {
    prefix: 'one',
    numChainId: 1666600000,
    chainId: '0x63564C40',
    order: 1,
    isToken: true,
    isSupportedNFT: true,
    nftStandard: 'HRC721',
    standard: 'HRC20',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',
    // nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    isWeb3: true,
    isFee: true,
    icon: 'app_harmony',

    id: 'harmony',
    name: 'Harmony',
    logo: COIN_IMAGE.ONE,
    symbol: 'ONE',
    chain: CHAIN_TYPE.harmony,
    tokenStandard: 'ONE HRC20 HRC721',
    rpcURL: 'https://api.harmony.one',
    scan: 'https://explorer.harmony.one',
  },
  conflux: {
    isLibrary: true,
    defaultFee: 0.00005,

    prefix: 'cfx',
    standard: 'CRC20',
    nftStandard: 'CRC721',
    isToken: true,
    order: 2,

    id: 'conflux-token',
    name: 'Conflux',
    icon: 'app_conflux',
    logo: COIN_IMAGE.CFX,
    symbol: 'CFX',
    chain: CHAIN_TYPE.conflux,
    tokenStandard: 'CFX CRC20 CRC721',
    scan: 'https://www.confluxscan.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'address',
    scanBlockPrefix: 'block',
  },
  optimism: {
    // defaultFee: 882000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    numChainId: 10,
    chainId: '0xA',
    // numChainId: 69,
    // chainId: '0x45',

    order: 2,
    isToken: true,
    standard: 'ERC20 OPT',
    nftStandard: 'ERC721 OPT',
    // balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    icon: 'app_optimism',
    id: 'ethereum',
    name: 'Optimism',
    shortName: 'Optimism',
    logo: COIN_IMAGE.OP,
    symbol: 'ETH',
    replacementSymbol: 'OP',
    chain: CHAIN_TYPE.optimism,
    tokenStandard: 'ETH ERC20 ERC721',
    // rpcURL: 'https://mainnet.optimism.io',
    rpcURL: 'https://mainnet.optimism.io',
    scan: 'https://optimistic.etherscan.io',
  },
  boba: {
    // defaultFee: 80000000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    numChainId: 288,
    chainId: '0x120',

    order: 2,
    isToken: true,
    standard: 'ERC20 BOBA',
    nftStandard: 'ERC721 BOBA',
    // multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    icon: 'app_boba',
    id: 'ethereum',
    name: 'Boba Network',
    shortName: 'Boba Network',
    logo: COIN_IMAGE.BOBA,
    symbol: 'ETH',
    replacementSymbol: 'BOBA',
    chain: CHAIN_TYPE.boba,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.boba.network',
    scan: 'https://blockexplorer.boba.network',
  },
  arbitrum: {
    defaultFee: 7000000,
    isL2: true,
    numChainId: 42161,
    chainId: '0xa4b1',
    // numChainId: 421611,
    // chainId: '0x66EEB',

    order: 2,
    isToken: true,
    standard: 'ERC20 ARB',
    nftStandard: 'ERC721 ARB',
    // balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    icon: 'app_arbitrum',
    id: 'ethereum',
    name: 'Arbitrum',
    shortName: 'Arbitrum',
    logo: COIN_IMAGE.ETHARB,
    symbol: 'ETH',
    replacementSymbol: 'ARB',
    chain: CHAIN_TYPE.arbitrum,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://arb1.arbitrum.io/rpc',
    // rpcURL: 'https://rinkeby.arbitrum.io/rpc',
    scan: 'https://arbiscan.io',
    // nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC'
  },
  arbitrumXdai: {
    isL2: true,
    numChainId: 200,
    chainId: '0xC8',

    order: 2,
    isSupportedNFT: true,
    isToken: true,
    standard: 'ERC20 AOX',
    nftStandard: 'ERC721 AOX',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    // nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    isWeb3: true,
    isFee: true,
    icon: 'app_arbitrum_xdai',
    id: 'xdai',
    name: 'Arbitrum on xDai',
    shortName: 'Arbitrum on xDai',
    logo: COIN_IMAGE.ETHA0X,
    symbol: 'XDAI',
    replacementSymbol: 'AOX',
    chain: CHAIN_TYPE.arbitrumXdai,
    tokenStandard: 'XDAI XRC20 XRC721',
    rpcURL: 'https://arbitrum.xdaichain.com',
    scan: 'https://blockscout.com/xdai/aox',
  },

  aurora: {
    isL2: true,
    defaultFee: 0,

    numChainId: 1313161554,
    chainId: '0x4e454152',
    order: 2,
    isToken: true,
    isSupportedNFT: true,
    nftStandard: 'AURORA721',
    standard: 'AURORA20',
    // balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // //nftMint: '0xc4cAd0938256ABA4417c565044Be2c2EB77096cb',

    isWeb3: true,
    icon: 'app_aurora',

    id: 'aurora-near',
    name: 'Aurora',
    shortName: 'Aurora',
    logo: COIN_IMAGE.AURORA,
    symbol: 'AURORA',
    chain: CHAIN_TYPE.aurora,
    tokenStandard: 'AURORA AURORA20 AURORA721',
    rpcURL: 'https://mainnet.aurora.dev',
    scan: 'https://explorer.mainnet.aurora.dev',
  },
  ton: {
    id: 'the-open-network',
    name: 'The Open Network',
    shortName: 'TON',
    logo: COIN_IMAGE.TON,
    isToken: false,
    isMemo: true,
    symbol: 'TON',
    chain: CHAIN_TYPE.ton,
    tokenStandard: 'TON TON721',
    rpcURL: 'https://toncenter.com/api/v2/jsonRPC',
    scan: 'https://tonscan.org',
    icon: 'app_ton',
  },

  // ? Recent release
  cronos: {
    id: 'crypto-com-chain',
    chain: CHAIN_TYPE.cronos,
    name: 'Cronos',
    shortName: 'CRO',
    isToken: true,
    standard: 'CRO',
    numChainId: 25,
    chainId: '0x19',
    symbol: 'CRO',
    icon: 'app_cronos',
    tokenStandard: 'CRC20 CRC721',
    rpcURL: 'https://evm-cronos.crypto.org',
    scan: 'https://cronoscan.com',
    logo: COIN_IMAGE.CRO,
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // nftMint: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multiTransferContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
  },
  bittorrent: {
    numChainId: 199,
    chainId: '0xc7',
    isToken: true,
    standard: 'BTT',
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'bittorrent',
    name: 'BitTorrent Chain',
    shortName: 'BTT',
    icon: 'app_bitorrent',
    logo: COIN_IMAGE.BTT,
    symbol: 'BTT',
    chain: CHAIN_TYPE.bittorrent,
    tokenStandard: 'BTT BRC20 BRC721',
    balanceContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    // nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    rpcURL: 'https://rpc.bt.io',
    scan: 'https://scan.bt.io/#',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'address',
  },
  theta: {
    standard: 'THETA',
    id: 'theta-token',
    name: 'Theta Network',
    shortName: 'THETA',
    icon: 'app_thetanetwork',
    logo: COIN_IMAGE.THETA,
    symbol: 'THETA',
    chain: CHAIN_TYPE.theta,
    tokenStandard: 'TNT20 TNT721',
    rpcURL: 'https://theta-bridge-rpc.thetatoken.org/rpc',
    scan: 'https://explorer.thetatoken.org',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    // isFee: true
  },
  thetaFuel: {
    numChainId: 361,
    chainId: '0x169',
    isToken: true,
    standard: 'TFUEL',
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'theta-fuel',
    name: 'Theta Network EVM',
    shortName: 'THETA',
    icon: 'app_thetanetwork',
    logo: COIN_IMAGE.TFUEL,
    symbol: 'TFUEL',
    chain: CHAIN_TYPE.thetaFuel,
    tokenStandard: 'TNT20 TNT721',
    rpcURL: 'https://eth-rpc-api.thetatoken.org/rpc',
    scan: 'https://explorer.thetatoken.org',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    balanceContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    // nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0xf7eee3a8363731c611a24cddfcbcade9c153cfe8',
  },
  platon: {
    id: 'platon-network',
    numChainId: 210425,
    chainId: '0x335F9',
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'LAT',
    name: 'PlatON Network',
    shortName: 'LAT',
    icon: 'app_platon',
    logo: COIN_IMAGE.LAT,
    symbol: 'LAT',
    chain: CHAIN_TYPE.platon,

    tokenStandard: 'PRC20 PRC721',
    rpcURL: 'https://openapi2.platon.network/rpc',
    scan: 'https://scan.platon.network',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // //nftMint: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multiTransferContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
  },
  moonbeam: {
    numChainId: 1284,
    chainId: '0x504',
    isToken: true,
    standard: 'GLMR',
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'moonbeam',
    name: 'Moonbeam',
    shortName: 'GLMR',
    icon: 'app_moonbeam',
    logo: COIN_IMAGE.GLMR,
    symbol: 'GLMR',
    chain: CHAIN_TYPE.moonbeam,
    tokenStandard: 'MERC20 MERC721',
    rpcURL: 'https://rpc.api.moonbeam.network',
    scan: 'https://moonscan.io',
    balanceContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    // //nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  },
  aptosLabs: {
    environment: 'mainnet',
    chainId: 'aptoslabs',
    // isToken: true,
    standard: 'APT',
    id: 'aptos',
    name: 'Aptos',
    shortName: 'APT',
    icon: 'app_aptos',
    logo: COIN_IMAGE.APT,
    symbol: 'APT',
    chain: CHAIN_TYPE.aptosLabs,
    tokenStandard: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.mainnet.aptoslabs.com',
    scan: 'https://tracemove.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
  },
  injective: {
    prefix: 'inj',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'injective-1',
    id: 'injective',
    name: 'Injective',
    icon: 'app_injective',
    symbol: 'INJ',
    logo: COIN_IMAGE.INJ,
    chain: CHAIN_TYPE.injective,
    tokenStandard: 'INJ',
    scan: 'https://www.mintscan.io/injective',
    rpcURL: 'https://tm.injective.network',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  osmosis: {
    prefix: 'osmo',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'osmosis-1',
    id: 'osmosis',
    name: 'Osmosis',
    icon: 'app_omosis',
    symbol: 'OSMO',
    logo: COIN_IMAGE.OSMO,
    chain: CHAIN_TYPE.osmosis,
    tokenStandard: 'Osmosis',
    scan: 'https://www.mintscan.io/osmosis',
    rpcURL: 'https://rpc-osmosis.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  evmos: {
    prefix: 'evmos',
    path: 60,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'evmos_9001-2',
    id: 'evmos',
    name: 'Evmos',
    icon: 'app_evmos',
    symbol: 'EVMOS',
    logo: COIN_IMAGE.EVMOS,
    chain: CHAIN_TYPE.evmos,
    tokenStandard: 'EVMOS',
    scan: 'https://www.mintscan.io/evmos',
    rpcURL: 'https://rpc-evmos.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  juno: {
    prefix: 'juno',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'juno-1',
    id: 'juno-network',
    name: 'Juno Network',
    icon: 'app_juno',
    symbol: 'JUNO',
    logo: COIN_IMAGE.JUNO,
    chain: CHAIN_TYPE.juno,
    tokenStandard: 'JUNO',
    scan: 'https://www.mintscan.io/juno',
    rpcURL: 'https://rpc-osmosis.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  agoric: {
    prefix: 'agoric',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'agoric-3',
    id: 'agoric',
    name: 'Agoric',
    icon: 'app_agoric',
    symbol: 'BLD',
    logo: COIN_IMAGE.BLD,
    chain: CHAIN_TYPE.agoric,
    tokenStandard: 'BLD',
    scan: 'https://bigdipper.live/agoric',
    rpcURL: 'https://rpc-agoric.keplr.app',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'accounts',
  },
  // kaneda: {},
  oasis: {
    numChainId: 42262,
    chainId: '0xa516',
    order: 0,
    isToken: true,

    standard: 'ORC20',
    nftStandard: 'ORC721',
    balanceContract: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',

    isWeb3: true,
    isFee: true,
    icon: 'app_oasis',
    id: 'oasis-network',
    name: 'Oasis Network',
    shortName: 'ROSE',
    logo: COIN_IMAGE.ROSE,
    symbol: 'ROSE',
    chain: CHAIN_TYPE.oasis,
    tokenStandard: 'ROSE ORC20 ORC721',
    rpcURL: 'https://emerald.oasis.dev',
    scan: 'https://explorer.emerald.oasis.dev/',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  kujira: {
    prefix: 'kujira',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'kaiyo-1',
    id: 'kujira',
    name: 'Kujira',
    icon: 'app_kujira',
    symbol: 'KUJI',
    logo: COIN_IMAGE.KUJI,
    chain: CHAIN_TYPE.kujira,
    tokenStandard: 'KUJI',
    scan: 'https://www.mintscan.io/kujira',
    rpcURL: 'https://rpc.kaiyo.kujira.setten.io',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  stargaze: {
    prefix: 'stars',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'stargaze-1',
    id: 'stargaze',
    name: 'Stargaze',
    icon: 'app_stagraze',
    symbol: 'STARS',
    logo: COIN_IMAGE.STARS,
    chain: CHAIN_TYPE.stargaze,
    tokenStandard: 'STARS',
    scan: 'https://www.mintscan.io/stargaze',
    rpcURL: 'https://rpc-stargaze.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  umee: {
    prefix: 'umee',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'umee-1',
    id: 'umee',
    name: 'Umee',
    icon: 'app_umee',
    symbol: 'UMEE',
    logo: COIN_IMAGE.UMEE,
    chain: CHAIN_TYPE.umee,
    tokenStandard: 'UMEE',
    scan: 'https://www.mintscan.io/umee',
    rpcURL: 'https://rpc-umee-ia.cosmosia.notional.ventures/',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  stride: {
    prefix: 'stride',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'stride-1',
    id: 'stride',
    name: 'Stride',
    icon: 'app_stride',
    symbol: 'STRD',
    logo: COIN_IMAGE.STRD,
    chain: CHAIN_TYPE.stride,
    tokenStandard: 'STRD',
    scan: 'https://www.mintscan.io/stride',
    rpcURL: 'https://rpc-stride.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  aptos: {
    environment: 'testnet',
    // isDevnet: true,
    chainId: 'ait-3',
    // isToken: true,
    standard: 'APT',
    id: 'aptos-test',
    name: 'Aptos Testnet',
    shortName: 'APT',
    icon: 'app_aptos',
    logo: COIN_IMAGE.APT,
    symbol: 'APT-TEST',
    chain: CHAIN_TYPE.aptos,
    tokenStandard: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.testnet.aptoslabs.com',
    scan: 'https://testnet.tracemove.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
  },
  aptosDev: {
    environment: 'devnet',
    // isDevnet: true,
    chainId: 'ait-dev',
    // isToken: true,
    standard: 'APT',
    id: 'aptos-dev',
    name: 'Aptos DevNet',
    shortName: 'APT',
    icon: 'app_aptos',
    logo: COIN_IMAGE.APT,
    symbol: 'APT-DEV',
    chain: CHAIN_TYPE.aptosDev,
    tokenStandard: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.devnet.aptoslabs.com',
    scan: 'https://devnet.tracemove.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
  },

  sui: {
    environment: 'devnet',
    chainId: 'sui',
    standard: 'SUI',
    id: 'sui',
    name: 'Sui',
    shortName: 'Sui',
    icon: 'app_sui',
    logo: COIN_IMAGE.SUI,
    symbol: 'SUI',
    chain: CHAIN_TYPE.sui,
    tokenStandard: 'SUI',
    rpcURL: 'https://gateway.devnet.sui.io:443',
    scan: 'https://explorer.devnet.sui.io',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'addresses',
  },
  sei: {
    environment: 'testnet',
    prefix: 'sei',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: true,
    isSupportedNFT: true,

    chainId: 'atlantic-1',
    id: 'sei',
    name: 'Sei Testnet',
    icon: 'app_sei',
    symbol: 'SEI',
    logo: COIN_IMAGE.SEI,
    chain: CHAIN_TYPE.sei,
    tokenStandard: 'Sei Chain',
    scan: 'https://sei.explorers.guru',
    rpcURL: 'https://sei-chain-incentivized.com/sei-chain-app',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
  },
  archway: {
    environment: 'devnet',
    prefix: 'archway',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,
    chainId: 'constantine-1',
    id: 'constantine-1',
    name: 'Archway',
    icon: 'app_archway',
    symbol: 'CONST',
    logo: COIN_IMAGE.CONST,
    chain: CHAIN_TYPE.archway,
    tokenStandard: 'Constantine Testnet',
    scan: 'https://explorer.constantine-1.archway.tech',
    rpcURL: 'https://rpc.constantine-1.archway.tech',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'account',
  },
};
